package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("company", "cname", Company.class);
		// Composite Primary Key order: AdminName,id
		arp.addMapping("news", "AdminName,id", News.class);
		arp.addMapping("recruit", "recruitid", Recruit.class);
		arp.addMapping("request", "id", Request.class);
		// Composite Primary Key order: sname,stuID
		arp.addMapping("stu", "sname,stuID", Stu.class);
		arp.addMapping("useradmin", "adminName", Useradmin.class);
		arp.addMapping("whereabouts", "id", Whereabouts.class);
	}
}

