package model;

import model.base.BaseRecruit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Recruit extends BaseRecruit<Recruit> {
	public static final Recruit dao = new Recruit().dao();
}
