package model;

import model.base.BaseRequest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Request extends BaseRequest<Request> {
	public static final Request dao = new Request().dao();
}
