package model;

import model.base.BaseUseradmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Useradmin extends BaseUseradmin<Useradmin> {
	public static final Useradmin dao = new Useradmin().dao();
}
