package model;

import model.base.BaseWhereabouts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Whereabouts extends BaseWhereabouts<Whereabouts> {
	public static final Whereabouts dao = new Whereabouts().dao();
}
