package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAdminName(java.lang.String AdminName) {
		set("AdminName", AdminName);
		return (M)this;
	}
	
	public java.lang.String getAdminName() {
		return getStr("AdminName");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setNewsTime(java.lang.String newsTime) {
		set("newsTime", newsTime);
		return (M)this;
	}
	
	public java.lang.String getNewsTime() {
		return getStr("newsTime");
	}

}
