package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRecruit<M extends BaseRecruit<M>> extends Model<M> implements IBean {

	public M setRecruitid(java.lang.Integer recruitid) {
		set("recruitid", recruitid);
		return (M)this;
	}
	
	public java.lang.Integer getRecruitid() {
		return getInt("recruitid");
	}

	public M setMajor(java.lang.String major) {
		set("major", major);
		return (M)this;
	}
	
	public java.lang.String getMajor() {
		return getStr("major");
	}

	public M setCname(java.lang.String cname) {
		set("cname", cname);
		return (M)this;
	}
	
	public java.lang.String getCname() {
		return getStr("cname");
	}

	public M setPosition(java.lang.String position) {
		set("position", position);
		return (M)this;
	}
	
	public java.lang.String getPosition() {
		return getStr("position");
	}

	public M setSalary(java.lang.Integer salary) {
		set("salary", salary);
		return (M)this;
	}
	
	public java.lang.Integer getSalary() {
		return getInt("salary");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	public M setRecruitTime(java.lang.String recruitTime) {
		set("recruitTime", recruitTime);
		return (M)this;
	}
	
	public java.lang.String getRecruitTime() {
		return getStr("recruitTime");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setDegree(java.lang.String degree) {
		set("degree", degree);
		return (M)this;
	}
	
	public java.lang.String getDegree() {
		return getStr("degree");
	}

	public M setInf(java.lang.String inf) {
		set("inf", inf);
		return (M)this;
	}
	
	public java.lang.String getInf() {
		return getStr("inf");
	}

}
