package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUseradmin<M extends BaseUseradmin<M>> extends Model<M> implements IBean {

	public M setAdminName(java.lang.String adminName) {
		set("adminName", adminName);
		return (M)this;
	}
	
	public java.lang.String getAdminName() {
		return getStr("adminName");
	}

	public M setAdminPassword(java.lang.String adminPassword) {
		set("adminPassword", adminPassword);
		return (M)this;
	}
	
	public java.lang.String getAdminPassword() {
		return getStr("adminPassword");
	}

}
