package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRequest<M extends BaseRequest<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRecruitId(java.lang.Integer recruitId) {
		set("recruitId", recruitId);
		return (M)this;
	}
	
	public java.lang.Integer getRecruitId() {
		return getInt("recruitId");
	}

	public M setCname(java.lang.String cname) {
		set("cname", cname);
		return (M)this;
	}
	
	public java.lang.String getCname() {
		return getStr("cname");
	}

	public M setSname(java.lang.String sname) {
		set("sname", sname);
		return (M)this;
	}
	
	public java.lang.String getSname() {
		return getStr("sname");
	}

	public M setResume(java.lang.String resume) {
		set("resume", resume);
		return (M)this;
	}
	
	public java.lang.String getResume() {
		return getStr("resume");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
